# "tec" stands for trustbridge ethereum channel

version: '3.5'

networks:
  internal:
    name: tec-internal

volumes:
  unlock:
    name: tec-unlock-files

x-services:
  deployer: &deployer
    image: tec/deployer
    container_name: tec-deployer
    build:
      context: ${dockerstagedir:-.}/contract-deployer
      dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-wrapper.sh", "/deployer/docker/entrypoint.sh"]
    command: -d -e scripts/channel-nodes-pairing.js
    volumes:
      - '${dockerstagedir:-.}/contract-deployer:/deployer'
      - '${dockerstagedir:-.}/contract:/tmp/contract'
      - '${dockerstagedir:-.}/entrypoint-wrapper.sh:/entrypoint-wrapper.sh'
      - 'unlock:/tmp/unlock-file'
    networks:
      - internal

  channel-api: &channel-api
    image: tec/channel-api
    container_name: tec-channel-api
    build:
     context: '${dockerstagedir:-.}/channel-api'
     dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-wrapper.sh", "/channel-api/docker/entrypoint.sh"]
    command: server
    volumes:
     - '/channel-api/node_modules'
     - '${dockerstagedir:-.}/channel-api:/channel-api'
     - '${dockerstagedir:-.}/entrypoint-wrapper.sh:/entrypoint-wrapper.sh'
     - 'unlock:/tmp/unlock-file'
    networks:
      - internal
    ports:
      - '9090:9090'

  websub-hub: &websub-hub
    image: tec/websub-hub
    container_name: tec-websub-hub
    build:
      context: ${dockerstagedir:-.}/websub-hub
      dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-wrapper.sh", "/websub-hub/docker/entrypoint.sh"]
    command: server
    networks:
      - internal
    depends_on:
      - localstack
    volumes:
      - "${dockerstagedir:-.}/websub-hub:/websub-hub"
      - '${dockerstagedir:-.}/entrypoint-wrapper.sh:/entrypoint-wrapper.sh'
      - 'unlock:/tmp/unlock-file'

  contract-event-listener: &contract-event-listener
    image: tec/contract-event-listener
    container_name: contract-event-listener
    build:
      context: ${dockerstagedir:-.}/contract-event-listener
      dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-wrapper.sh", "/contract-event-listener/docker/entrypoint.sh"]
    command: worker
    env_file:
      - aws-credentials.env
    networks:
      - internal
    volumes:
      - ${dockerstagedir:-.}/contract-event-listener:/contract-event-listener
      - '${dockerstagedir:-.}/entrypoint-wrapper.sh:/entrypoint-wrapper.sh'
      - 'unlock:/tmp/unlock-file'

services:
  localstack:
    image: localstack/localstack
    container_name: tec-localstack
    env_file: localstack.env
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'
      - 'unlock:/tmp/unlock-file'
      - '/var/run/docker.sock:/var/run/docker.sock'

  ganache-cli:
    image: trufflesuite/ganache-cli
    container_name: tec-ganache-cli
    networks:
      - internal
    command: >
        ganache-cli
        --quiet
        --hostname 0.0.0.0
        --port 8585
        --networkId 15
        --hardfork petersburg
        --blockTime 0
        --accounts 5
        --deterministic
        --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect"

  deployer-participant-au:
    <<: *deployer
    container_name: tec-deployer-participant-au
    env_file:
      - aws-credentials.env
      - deployer-participant-au.env
    environment:
      REQUIRED_UNLOCK_FILES: AWS

  deployer-participant-gb:
    <<: *deployer
    container_name: tec-deployer-participant-gb
    env_file:
      - aws-credentials.env
      - deployer-participant-gb.env
    environment:
      REQUIRED_UNLOCK_FILES: AWS

  channel-api-au:
    <<: *channel-api
    container_name: tec-channel-api-au
    env_file:
      - aws-credentials.env
      - channel-api-au.env
    ports:
      - '9090:9090'
    environment:
      REQUIRED_UNLOCK_FILES: AWS channel-node-participant-au

  channel-api-gb:
    <<: *channel-api
    container_name: tec-channel-api-gb
    env_file:
      - aws-credentials.env
      - channel-api-gb.env
    ports:
      - '9091:9091'
    environment:
      REQUIRED_UNLOCK_FILES: AWS channel-node-participant-gb

  websub-hub-au:
    <<: *websub-hub
    container_name: tec-websub-hub-au
    env_file:
      - websub-hub.default.env
      - websub-hub-au.env
    environment:
      REQUIRED_UNLOCK_FILES: AWS

  websub-hub-gb:
    <<: *websub-hub
    container_name: tec-websub-hub-gb
    env_file:
      - websub-hub.default.env
      - websub-hub-gb.env
    environment:
      REQUIRED_UNLOCK_FILES: AWS

  contract-event-listener-au:
    <<: *contract-event-listener
    container_name: tec-contract-event-listener-au
    environment:
      YAML_CONFIG_FILE_VALUE: ${YAML_CONFIG_FILE_VALUE_AU}
      REQUIRED_UNLOCK_FILES: AWS channel-node-participant-au

  contract-event-listener-gb:
    <<: *contract-event-listener
    container_name: tec-contract-event-listener-gb
    environment:
      YAML_CONFIG_FILE_VALUE: ${YAML_CONFIG_FILE_VALUE_GB}
      REQUIRED_UNLOCK_FILES: AWS channel-node-participant-gb
